name: Test Installation Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar manualmente el workflow desde la interfaz de GitHub

jobs:
  test-script:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run installation script
        run: ./install.sh
